name: Manual Release

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: 'Enter next release version'
        required: false

jobs:
  manual-release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools_scm build

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(python -c "import setuptools_scm; print(setuptools_scm.get_version().split('.dev')[0])")

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.next_version || steps.get_version.outputs.VERSION }}
        release_name: Release v${{ github.event.inputs.next_version || steps.get_version.outputs.VERSION }}
        body: Manual release for version v${{ github.event.inputs.next_version || steps.get_version.outputs.VERSION }}.
        draft: false
        prerelease: false

    - name: Fetch new tag
      run: git fetch origin

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
